### ISSUE TITLE
Add natural support

### ISSUE THREAD

**Issue by nickfengqian** [autodiff-cs207/AutoDiff#1]
We should add natural support to constants:

For example, the following code does not work:
y=Variable('x')+6

We have to do right now with our code
y=Variable('x')+Constant('x',6)

This makes sense when we are doing back-propagation or a parameter-estimating task where parameters need to be updated. But when we are simply doing root finding where parameters are just parameters and are not designed to be updated, this way of initializing is redundant.

Feng

**Comment by talwarabhimanyu** [comment]
I agree, the TF also needs us to fix this. I'll fix it.

**Comment by nickfengqian** [comment]
Thanks man
